'use strict';

/**
 * APK export: produces a ready-to-build Cordova project as a zip.
 *
 * We do not compile the APK here - that needs the Android SDK and a signing
 * key, neither of which belongs on a web server. What we ship is a project
 * that builds with two commands and needs zero code edits, which is the part
 * that is actually tedious to get right.
 */

const bundler = require('./bundler');
const { zip } = require('./zip');

const slugify = (s) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'meamus-game';

/** Reverse-DNS package id, e.g. "Astro Salvage" -> com.meamus.astrosalvage */
function packageId(title, prefix = 'com.meamus') {
  const clean = String(title).toLowerCase().replace(/[^a-z0-9]/g, '') || 'game';
  const safe = /^[a-z]/.test(clean) ? clean : `g${clean}`;
  return `${prefix}.${safe}`;
}

function configXml(spec, opts) {
  const title = bundler.escapeHtml(spec.gameConfig.title);
  const description = bundler.escapeHtml(spec.gameConfig.description);
  return `<?xml version='1.0' encoding='utf-8'?>
<widget id="${opts.packageId}" version="${opts.version}" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>${title}</name>
    <description>${description}</description>
    <author email="${bundler.escapeHtml(opts.authorEmail)}" href="${bundler.escapeHtml(opts.authorUrl)}">${bundler.escapeHtml(opts.author)}</author>

    <content src="index.html" />
    <!-- The game only needs the Phaser CDN; everything else is inlined. -->
    <allow-navigation href="https://cdn.jsdelivr.net/*" />
    <access origin="https://cdn.jsdelivr.net/*" />

    <preference name="Orientation" value="${opts.orientation}" />
    <preference name="Fullscreen" value="true" />
    <preference name="BackgroundColor" value="0xff06080f" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="AndroidInsecureFileModeEnabled" value="false" />

    <platform name="android">
        <preference name="android-minSdkVersion" value="24" />
        <preference name="android-targetSdkVersion" value="34" />
        <preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/icon/icon.png" />
        <preference name="AndroidWindowSplashScreenBackground" value="#06080f" />
        <!-- Adaptive icon slots. Drop your art in and rebuild. -->
        <icon density="ldpi" src="res/icon/icon.png" />
        <icon density="mdpi" src="res/icon/icon.png" />
        <icon density="hdpi" src="res/icon/icon.png" />
        <icon density="xhdpi" src="res/icon/icon.png" />
        <icon density="xxhdpi" src="res/icon/icon.png" />
        <icon density="xxxhdpi" src="res/icon/icon.png" />
    </platform>
</widget>
`;
}

function packageJson(spec, opts) {
  return JSON.stringify({
    name: opts.slug,
    displayName: spec.gameConfig.title,
    version: opts.version,
    description: spec.gameConfig.description,
    main: 'index.js',
    scripts: {
      'prepare:android': 'cordova platform add android',
      'build:debug': 'cordova build android',
      'build:release': 'cordova build android --release',
      run: 'cordova run android'
    },
    devDependencies: { cordova: '^12.0.0' },
    cordova: { platforms: ['android'] },
    private: true
  }, null, 2);
}

function buildScript(opts) {
  return `#!/usr/bin/env bash
# Build ${opts.slug} as an Android APK.
# Prerequisites: Node 18+, JDK 17, Android SDK (platform 34 + build-tools 34).
set -euo pipefail

npm install
npx cordova platform add android || true

if [ "\${1:-debug}" = "release" ]; then
  # A release build must be signed. Create the keystore once:
  #   keytool -genkey -v -keystore ${opts.slug}.keystore \\
  #     -alias ${opts.slug} -keyalg RSA -keysize 2048 -validity 10000
  # then fill in build.json (see README_APK.md) before running this.
  npx cordova build android --release --buildConfig build.json
  echo "APK: platforms/android/app/build/outputs/apk/release/app-release.apk"
else
  npx cordova build android
  echo "APK: platforms/android/app/build/outputs/apk/debug/app-debug.apk"
fi
`;
}

function readme(spec, opts) {
  return `# ${spec.gameConfig.title} - Android build

Generated by meamus. This is a complete Cordova project: the game is already
in \`www/index.html\` as a single self-contained file.

## Prerequisites

| Tool | Version |
|---|---|
| Node.js | 18 or newer |
| JDK | 17 (Temurin works) |
| Android SDK | platform 34, build-tools 34.0.0 |
| Gradle | bundled with Cordova |

Set \`ANDROID_HOME\` (or \`ANDROID_SDK_ROOT\`) and \`JAVA_HOME\` before building.

## Debug build

\`\`\`bash
./build.sh
# -> platforms/android/app/build/outputs/apk/debug/app-debug.apk
\`\`\`

Install on a connected device with \`adb install -r <path-to-apk>\`.

## Release build (Play Store)

1. Create a keystore once and keep it safe - losing it means you can never
   update the listing:

   \`\`\`bash
   keytool -genkey -v -keystore ${opts.slug}.keystore \\
     -alias ${opts.slug} -keyalg RSA -keysize 2048 -validity 10000
   \`\`\`

2. Create \`build.json\` next to \`config.xml\`:

   \`\`\`json
   {
     "android": {
       "release": {
         "keystore": "${opts.slug}.keystore",
         "storePassword": "YOUR_STORE_PASSWORD",
         "alias": "${opts.slug}",
         "password": "YOUR_KEY_PASSWORD",
         "keystoreType": ""
       }
     }
   }
   \`\`\`

   Do not commit \`build.json\` or the keystore.

3. Build and upload:

   \`\`\`bash
   ./build.sh release
   \`\`\`

## What to customise before publishing

- \`res/icon/icon.png\` - replace the placeholder with a 1024x1024 icon.
- \`config.xml\` - the package id is \`${opts.packageId}\`; change it if you own
  a different domain. It is permanent once published.
- Orientation is set to \`${opts.orientation}\`.
- Ad SDK: the game calls \`MEAMUS.ads.showBanner / showInterstitial /
  showRewarded\`. Wire your network into those three functions and set
  \`MEAMUS.ads.enabled = true\`.

## Offline builds

The game loads Phaser from jsDelivr. To ship a fully offline APK, download
\`phaser.min.js\` into \`www/\` and change the \`<script src>\` in
\`www/index.html\` to \`phaser.min.js\`.
`;
}

/** 1x1 transparent PNG - a valid placeholder so the build never fails on a missing icon. */
const PLACEHOLDER_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
  'base64'
);

/**
 * @param {object} spec normalised GameSpec
 * @param {object} [options] packageId / version / author / orientation overrides
 * @returns {{filename:string, buffer:Buffer, files:string[]}}
 */
function buildProject(spec, options = {}) {
  const slug = slugify(spec.gameConfig.title);
  const opts = {
    slug,
    packageId: options.packageId || packageId(spec.gameConfig.title),
    version: options.version || '1.0.0',
    author: options.author || 'meamus',
    authorEmail: options.authorEmail || 'hello@example.com',
    authorUrl: options.authorUrl || 'https://example.com',
    // Puzzle games read better upright; action games default to landscape.
    orientation: options.orientation || (spec.gameConfig.genre === 'puzzle' ? 'portrait' : 'landscape')
  };

  const html = bundler.bundle(spec);

  const files = [
    { name: 'www/index.html', data: html },
    { name: 'config.xml', data: configXml(spec, opts) },
    { name: 'package.json', data: packageJson(spec, opts) },
    { name: 'build.sh', data: buildScript(opts) },
    { name: 'README_APK.md', data: readme(spec, opts) },
    { name: 'res/icon/icon.png', data: PLACEHOLDER_PNG },
    { name: 'gamespec.json', data: JSON.stringify(spec, null, 2) },
    {
      name: '.gitignore',
      data: ['node_modules/', 'platforms/', 'plugins/', 'build.json', '*.keystore', ''].join('\n')
    }
  ];

  return {
    filename: `${slug}-cordova.zip`,
    buffer: zip(files),
    files: files.map((f) => f.name),
    packageId: opts.packageId,
    orientation: opts.orientation
  };
}

module.exports = { buildProject, packageId, slugify };
