'use strict';

/**
 * Parse + normalise a GameSpec.
 *
 * Claude is instructed to answer with raw JSON, but models occasionally wrap it
 * in prose or fences. extractJson() is deliberately forgiving; normaliseSpec()
 * then guarantees every downstream consumer (bundler, UI, APK exporter) sees
 * the same shape.
 */

const SPRITE_TYPES = ['player', 'enemy', 'collectible', 'obstacle', 'background', 'ui', 'effect'];
const AUDIO_TYPES = ['bgm', 'sfx', 'ui'];
const STYLES = ['pixel-art', 'vector', 'realistic', 'minimalist', 'cartoon'];
const DIFFICULTIES = ['easy', 'medium', 'hard'];

class SpecError extends Error {
  constructor(message, issues = []) {
    super(message);
    this.name = 'SpecError';
    this.status = 422;
    this.issues = issues;
  }
}

/** Pull the first balanced top-level JSON object out of arbitrary model text. */
function extractJson(text) {
  if (typeof text !== 'string') throw new SpecError('Model response was not text');

  let body = text.trim();

  // Strip a leading ```json fence if present.
  const fence = body.match(/^```(?:json)?\s*\n([\s\S]*?)\n?```\s*$/);
  if (fence) body = fence[1].trim();

  const start = body.indexOf('{');
  if (start === -1) throw new SpecError('No JSON object found in model response');

  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = start; i < body.length; i += 1) {
    const ch = body[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === '\\') escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') inString = true;
    else if (ch === '{') depth += 1;
    else if (ch === '}') {
      depth -= 1;
      if (depth === 0) {
        const slice = body.slice(start, i + 1);
        try {
          return JSON.parse(slice);
        } catch (err) {
          throw new SpecError(`Model returned malformed JSON: ${err.message}`);
        }
      }
    }
  }
  throw new SpecError('Model response contained an unterminated JSON object (likely truncated - raise ANTHROPIC_MAX_TOKENS)');
}

const str = (v, fallback = '') => (typeof v === 'string' && v.trim() ? v.trim() : fallback);
const arr = (v) => (Array.isArray(v) ? v : []);
const strArray = (v) => arr(v).map((x) => str(x)).filter(Boolean);
const oneOf = (v, allowed, fallback) => (allowed.includes(v) ? v : fallback);

function normaliseSpec(input, { source = 'ai' } = {}) {
  if (!input || typeof input !== 'object') throw new SpecError('Spec must be an object');

  const issues = [];
  const gc = input.gameConfig && typeof input.gameConfig === 'object' ? input.gameConfig : {};
  const code = input.gameCode && typeof input.gameCode === 'object' ? input.gameCode : {};
  const assets = input.assets && typeof input.assets === 'object' ? input.assets : {};
  const controls = input.controls && typeof input.controls === 'object' ? input.controls : {};

  const title = str(gc.title, 'Untitled Game');
  const javascript = str(code.javascript);

  if (!javascript) throw new SpecError('gameCode.javascript is empty - the model produced no game code', ['gameCode.javascript']);
  if (!/new\s+Phaser\.Game/.test(javascript)) issues.push('gameCode.javascript never instantiates Phaser.Game');
  if (!/class\s+GameScene/.test(javascript) && !/GameScene/.test(javascript)) issues.push('no GameScene found in gameCode.javascript');
  if (/\beval\s*\(/.test(javascript) || /new\s+Function\s*\(/.test(javascript)) {
    throw new SpecError('Generated code uses eval()/new Function() - rejected', ['gameCode.javascript']);
  }
  const lineCount = javascript.split('\n').length;
  if (lineCount > 2600) issues.push(`gameCode.javascript is ${lineCount} lines (guideline is <= 2000)`);

  const spec = {
    gameConfig: {
      title,
      genre: str(gc.genre, 'arcade').toLowerCase(),
      description: str(gc.description, `${title} - generated by meamus.`),
      difficulty: oneOf(str(gc.difficulty).toLowerCase(), DIFFICULTIES, 'medium'),
      estimatedPlayTime: str(gc.estimatedPlayTime, '2-5 minutes per session')
    },
    assets: {
      sprites: arr(assets.sprites).map((s, i) => ({
        name: str(s && s.name, `sprite_${i + 1}`),
        type: oneOf(str(s && s.type).toLowerCase(), SPRITE_TYPES, 'effect'),
        description: str(s && s.description, 'Procedural placeholder sprite.'),
        size: str(s && s.size, '32x32'),
        style: oneOf(str(s && s.style).toLowerCase(), STYLES, 'pixel-art')
      })),
      audio: arr(assets.audio).map((a, i) => ({
        name: str(a && a.name, `sound_${i + 1}`),
        type: oneOf(str(a && a.type).toLowerCase(), AUDIO_TYPES, 'sfx'),
        description: str(a && a.description, 'Placeholder sound.')
      }))
    },
    gameCode: {
      html: str(code.html),
      javascript,
      css: str(code.css)
    },
    controls: {
      keyboard: strArray(controls.keyboard),
      touch: strArray(controls.touch),
      mouse: strArray(controls.mouse)
    },
    mechanics: arr(input.mechanics)
      .map((m, i) => ({
        name: str(m && m.name, `Mechanic ${i + 1}`),
        description: str(m && m.description),
        implementation: str(m && m.implementation)
      }))
      .filter((m) => m.description || m.implementation),
    monetizationHooks: strArray(input.monetizationHooks),
    mobileOptimizations: strArray(input.mobileOptimizations),
    apkReady: input.apkReady === true
  };

  // Runtime metadata drives the bundler (templates opt into the shared kit).
  spec.runtime = {
    kit: input.runtime && input.runtime.kit === true,
    phaserVersion: str(input.runtime && input.runtime.phaserVersion, '3.60.0'),
    source
  };

  if (!spec.controls.keyboard.length) issues.push('no keyboard controls documented');
  if (!spec.controls.touch.length) issues.push('no touch controls documented');
  if (!spec.assets.sprites.length) issues.push('no sprite descriptions - asset pipeline has nothing to generate');
  if (!spec.monetizationHooks.length) issues.push('no monetization hooks declared');

  return { spec, issues };
}

module.exports = { extractJson, normaliseSpec, SpecError, SPRITE_TYPES, AUDIO_TYPES, STYLES, DIFFICULTIES };
